// Centralized Tailwind classes mapped directly to Design Tokens for App-wide styling consistency
export const TOKENS = {
  background: 'bg-[#fff8f7]',
  surface: 'bg-[#fff8f7]',
  primaryText: 'text-[#8a4d4e]',
  primaryBg: 'bg-[#8a4d4e]',
  primaryContainer: 'bg-[#d48c8c]',
  secondaryText: 'text-[#5d5a84]',
  secondaryBg: 'bg-[#5d5a84]',
  secondaryContainer: 'bg-[#d1ccfe]',
  tertiaryText: 'text-[#8d4d39]',
  tertiaryBg: 'bg-[#8d4d39]',
  tertiaryContainer: 'bg-[#d88c73]',
  errorText: 'text-[#ba1a1a]',
  errorBg: 'bg-[#ba1a1a]',
  errorContainer: 'bg-[#ffdad6]',
  onSurface: 'text-[#201a1a]',
  onSurfaceVariant: 'text-[#524343]',
  containerLow: 'bg-[#fef1f0]',
  container: 'bg-[#f8ebea]',
  containerHigh: 'bg-[#f2e5e4]',
  containerHighest: 'bg-[#ece0df]',
  cardRounded: 'rounded-3xl',
  panelRounded: 'rounded-2xl',
  fontBody: 'font-manrope',
  fontHeading: 'font-plus-jakarta',
  shadowGentle: 'shadow-gentle-md',
  slideAnim: 'transition-all duration-300 ease-in-out',
};
